trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'